POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNub3d5IiwiaWQiOiI2MjAwYzQ1OWZmMmIxNmQ5N2FkYjZjZWUiLCJpYXQiOjE2NDQyMTg3OTl9.dPovFVHnThYrUYuArNXUu4CgJnBsYHX9HHl5Jdg3Jkk

{
	"title": "Hello World",
	"author": "Hiiiiii",
	"url": "unknown",
	"likes": "12"
}